spring:
  application:
    name: rs-hardware-glass-and-electrical
  security:
    user:
      name: jawad
      password: jawad
  data:
    mongodb:
      uri: mongodb+srv://rshardware:rshardware2210@cluster0.n0btfbz.mongodb.net/rshardware?retryWrites=true&w=majority
      database: rshardware
server:
  port: ${PORT:8080}

togglz:
  enabled: true
  feature-enums: com.twoxplusone.rshardware.rs_hardware_glass_and_electrical.liveconfig.Payment
  console:
    enabled: true
    secured: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-components: ALWAYS